services:
    fl_qbjs_parser.json_deserializer:
        class: FL\QBJSParser\Serializer\JsonDeserializer
    fl_qbjs_parser.json_query_parser.doctrine_orm_parser:
        class: FL\QBJSParserBundle\Service\JsonQueryParser\DoctrineORMParser
        arguments:
            - "%fl_qbjs_parser.doctrine_classes_and_mappings%"
            - "@fl_qbjs_parser.json_deserializer"
    fl_qbjs_parser.javascript_builders:
        class: FL\QBJSParserBundle\Service\JavascriptBuilders
        arguments:
            - "%fl_qbjs_parser.builders%"
            - "%fl_qbjs_parser.doctrine_classes_and_mappings%"
            - "@event_dispatcher" # needs symfony/http-kernel in composer.json$
            - "@doctrine.orm.entity_manager"